# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainwindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("")
        MainWindow.resize(288, 352)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_1.setGeometry(QtCore.QRect(10, 10, 271, 16))
        self.title_1.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.title_1.setScaledContents(False)
        self.title_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.title_1.setObjectName("title_1")
        self.num_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.num_1.setGeometry(QtCore.QRect(10, 40, 271, 16))
        self.num_1.setText("")
        self.num_1.setObjectName("num_1")
        self.title_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_2.setGeometry(QtCore.QRect(10, 90, 281, 16))
        self.title_2.setObjectName("title_2")
        self.num_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.num_2.setGeometry(QtCore.QRect(10, 120, 271, 16))
        self.num_2.setText("")
        self.num_2.setObjectName("num_2")
        self.title_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_3.setGeometry(QtCore.QRect(10, 170, 271, 16))
        self.title_3.setObjectName("title_3")
        self.num_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.num_3.setGeometry(QtCore.QRect(10, 200, 271, 16))
        self.num_3.setText("")
        self.num_3.setObjectName("num_3")
        self.num_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.num_4.setGeometry(QtCore.QRect(10, 280, 271, 16))
        self.num_4.setText("")
        self.num_4.setObjectName("num_4")
        self.title_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_4.setGeometry(QtCore.QRect(80, 260, 271, 16))
        self.title_4.setObjectName("title_4")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 240, 211, 16))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 291, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 140, 291, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 220, 291, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.btn_1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(94, 320, 91, 24))
        self.btn_1.setObjectName("btn_1")
        self.line_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(-3, 300, 301, 20))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setObjectName("line_4")
        #MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " "))
        self.title_1.setText(_translate("MainWindow", "ПРИКЛАДНАЯ МАТЕМАТИКА И ИНФОРМАТИКА"))
        self.title_2.setText(_translate("MainWindow", "ИНФОРМАТИКА И ВЫЧИСЛИТЕЛЬНАЯ ТЕХНИКА"))
        self.title_3.setText(_translate("MainWindow", "КОМПЬЮТЕРНАЯ БЕЗОПАСНОСТЬ"))
        self.title_4.setText(_translate("MainWindow", "КОМПЬЮТЕРНАЯ БЕЗОПАСНОСТЬ"))
        self.label.setText(_translate("MainWindow", "Если бы зачисление было сегодня...\n"
""))
        self.btn_1.setText(_translate("MainWindow", "Узнать места"))
